@localhost = http://localhost:5147

GET {{localhost}}/api/customers
Accept: application/json

###

GET {{localhost}}/api/customers/1
Accept: application/json

###

POST {{localhost}}/api/customers
Content-Type: application/json

{
    "FirstName": "Steven",
    "Email": "stevenyandex.r"
}

###

PATCH {{localhost}}/api/customers?id=1
Content-Type: application/json

{
    "Email": "hellnep@yanedx.ru"
}

###

GET {{localhost}}/api/products
Accept: application/json

###

GET {{localhost}}/api/products/1
Accept: application/json

###

POST {{localhost}}/api/products
Content-Type: application/json

{
    "name": "Orange"
}

###

PATCH {{localhost}}/api/products?id=3
Content-Type: application/json

{
    "name": "Coconut",
    "description": "It's not beautiful!"
}