@localhost = http://localhost:5147

GET {{localhost}}/api/customers
Accept: application/json

###

GET {{localhost}}/api/customers/id=1
Accept: application/json

###

POST {{localhost}}/api/customers/create
Content-Type: application/json

{
    "Username": "Urojai"
}

###

PUT {{localhost}}/api/customers/change?id=1
Content-Type: application/json

{
    "Username": "Hellnep"
}

###

GET {{localhost}}/api/products
Accept: application/json

###

GET {{localhost}}/api/products/1
Accept: application/json

###

POST {{localhost}}/api/products/create
Content-Type: application/json

{
    "name": "Pedigry"
}

###

PUT {{localhost}}/api/products/change?id=3
Content-Type: application/json

{
    "name": "Coconut",
    "description": "It's not beautiful!"
}