@Purple_HostAddress = http://localhost:5147

GET {{Purple_HostAddress}}/api/customers
Accept: application/json

###

GET {{Purple_HostAddress}}/api/customers/id=1
Accept: application/json

###

POST {{Purple_HostAddress}}/api/customers/create
Content-Type: application/json

{
    "Username": "Urojai"
}

###

PUT {{Purple_HostAddress}}/api/customers/change?id=1
Content-Type: application/json

{
    "Username": "Hellnep"
}

###

GET {{Purple_HostAddress}}/api/products
Accept: application/json

###

GET {{Purple_HostAddress}}/api/products/id=1
Accept: application/json

###

POST {{Purple_HostAddress}}/api/products/create
Content-Type: application/json

{
    "name": "Milk",
    "description": "It's greatest milk forever"
}